name: "Reusable: Build Docker"

on:
  workflow_call:
    
    inputs:
      dockerfile_path:
        required: true
        type: string
    
    outputs:
      docker_tag:
        description: "Docker tag"
        value: ${{ jobs.build.outputs.docker_tag }}
    
    secrets:
      GCP_CREDS:
        required: true
      PROJECT_ID:
        required: true
      GAR_REGION:
        required: true
      FE_GAR_IMAGE_NAME:
        required: true
      FE_GAR_REPO_NAME:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      docker_tag: ${{ steps.set_tag.outputs.docker_tag }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Auth to GCP'
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDS }}

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2

      - name: 'Docker Auth To GAR'
        run: gcloud auth configure-docker "${{ secrets.GAR_REGION }}-docker.pkg.dev"

      - name: 'Build Docker Image'
        id: set_tag
        run: |
          DOCKER_TAG="${{ secrets.GAR_REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.FE_GAR_REPO_NAME }}/${{ secrets.FE_GAR_IMAGE_NAME }}:${{ github.sha }}"
          echo "DOCKER_TAG=$DOCKER_TAG" >> $GITHUB_ENV
           echo "docker_tag=${{ secrets.GAR_REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.FE_GAR_REPO_NAME }}/${{ secrets.FE_GAR_IMAGE_NAME }}:${{ github.sha }}" >> $GITHUB_OUTPUT
          docker build -t "$DOCKER_TAG" ${{ inputs.dockerfile_path }}
