name: "Frontend Service CI"

on:
  push:
    branches: [master]
    paths: ["frontend/**"]
  pull_request:
    branches: [master]
    paths: ["frontend/**"]

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  GAR_IMAGE_NAME: ${{ secrets.GAR_IMAGE_NAME }}
  GAR_REPO_NAME: ${{ secrets.GAR_REPO_NAME }}
  GAR_REGION: ${{ secrets.GAR_REGION }}

jobs:
  build-push:
    uses: ./.github/workflows/build-and-push.yaml
    with:
      context_path: ./frontend
      image_tag: ${{ github.sha }}
    secrets:
      PROJECT_ID: ${{ env.PROJECT_ID }}
      GAR_REGION: ${{ env.GAR_REGION }}
      GAR_IMAGE_NAME: ${{ env.GAR_IMAGE_NAME }}
      GAR_REPO_NAME: ${{ env.GAR_REPO_NAME }}
      GCP_CREDS: ${{ secrets.GCP_CREDS }}

  snyk-scan:
    uses: ./.github/workflows/reusable-snyk-scan.yaml
    needs: build-push
    with:
      context_path: ./frontend
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  trivy-scan:
    uses: ./.github/workflows/trivy-scan.yaml
    needs: build-push
    with:
      image_tag: ${{ github.sha }}
    secrets:
      PROJECT_ID: ${{ env.PROJECT_ID }}
      GAR_REGION: ${{ env.GAR_REGION }}
      GAR_IMAGE_NAME: ${{ env.GAR_IMAGE_NAME }}
      GAR_REPO_NAME: ${{ env.GAR_REPO_NAME }}
