name: 'frontend Service CI'

on:
  push:
    branches: [master]
    paths: ['frontend/**']
  pull_request:
    branches: [master]
    paths: ['frontend/**']

env:
  PROJECT_ID: '${{ secrets.PROJECT_ID }}'
  GAR_IMAGE_NAME: '${{ secrets.FE_GAR_IMAGE_NAME }}'
  GAR_REPO_NAME: '${{ secrets.FE_GAR_REPO_NAME }}'
  GAR_REGION: '${{ secrets.GAR_REGION }}'

permissions:
  contents: read
  id-token: write
  security-events: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Authenticate to GCP'
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDS }}'

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2

      - name: 'Docker Auth To GAR'
        run: gcloud auth configure-docker "${{ env.GAR_REGION }}-docker.pkg.dev"

      - name: 'Build Docker Image'
        run: |
          export DOCKER_TAG="${{ env.GAR_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPO_NAME }}/${{ env.GAR_IMAGE_NAME }}:${{ github.sha }}"
          docker build -t "$DOCKER_TAG" ./frontend
          echo "DOCKER_TAG=$DOCKER_TAG" >> $GITHUB_ENV

      - name: 'Call Trivy Reusable Workflow'
        uses: ./.github/workflows/trivy-scan.yaml
        with:
          image: ${{ env.DOCKER_TAG }}

      - name: 'Push Docker Image'
        run: docker push "$DOCKER_TAG"