name: Update Helm Image Tag

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      image_tag:
        required: true
        type: string
    secrets:
      GITHUB_TOKEN:
        required: true
      MANIFEST_REPO:
        required: true
      MANIFEST_BRANCH:
        required: false

jobs:
  update-manifest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout manifest repo
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.MANIFEST_REPO }}
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ secrets.MANIFEST_BRANCH || 'msater' }}
          path: manifest

      - name: Update image tag in Helm values.yaml
        run: |
          FILE="manifest/charts/${{ inputs.service_name }}/values.yaml"
          echo "Updating tag in: $FILE"

          # Safely replace the tag under image
          sed -i "s|\(tag:\s*\).*|\1${{ inputs.image_tag }}|" "$FILE"

      - name: Commit and push changes
        run: |
          cd manifest
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add charts/${{ inputs.service_name }}/values.yaml
          git commit -m "ci: update image tag for ${{ inputs.service_name }} to ${{ inputs.image_tag }}"
          git push