name: "Progress Tracking Service CI"

on:
  push:
    branches: [master]
    paths: ['backend/progress-tracking-service/**']
  # pull_request:
  #   branches: [master]
  #   paths: ['backend/progress-tracking-service/**']

permissions:
  contents: write
  id-token: write
  security-events: write

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  GAR_IMAGE_NAME: ${{ secrets.PTS_GAR_IMAGE_NAME }}
  GAR_REPO_NAME: ${{ secrets.PTS_GAR_REPO_NAME }}
  GAR_REGION: ${{ secrets.GAR_REGION }}

jobs:

  sonar:
    uses: ./.github/workflows/sonarqube-analysis.yaml
    with:
      context_path: './backend/progress-tracking-service'
      sonar_sources: './backend/progress-tracking-service/app'
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      ORG_SONAR: ${{ secrets.ORG_SONAR }}
      PROJECT_KEY_SONAR: ${{ secrets.PROJECT_KEY_SONAR }}

  build-push:
    uses: ./.github/workflows/build-and-push.yaml
    needs: sonar
    with:
      context_path: ./backend/progress-tracking-service
      image_tag: ${{ github.sha }}
    secrets:
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      GAR_REGION: ${{ secrets.GAR_REGION }}
      GAR_IMAGE_NAME: ${{ secrets.PTS_GAR_IMAGE_NAME }}
      GAR_REPO_NAME: ${{ secrets.PTS_GAR_REPO_NAME }}
      GCP_CREDS: ${{ secrets.GCP_CREDS }}

  # snyk-scan:
  #   uses: ./.github/workflows/snyk-scan.yaml
  #   needs: build-push
  #   with:
  #     context_path: ./backend/progress-tracking-service
  #   secrets:
  #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  trivy-scan:
    uses: ./.github/workflows/trivy-scan.yaml
    needs: build-push
    with:
      image_tag: ${{ github.sha }}
    secrets:
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      GAR_REGION: ${{ secrets.GAR_REGION }}
      GAR_IMAGE_NAME: ${{ secrets.PTS_GAR_IMAGE_NAME }}
      GAR_REPO_NAME: ${{ secrets.PTS_GAR_REPO_NAME }}
      GCP_CREDS: ${{ secrets.GCP_CREDS }}

  update-manifest:
    uses: ./.github/workflows/helm-tag.yaml
    needs: trivy-scan
    with:
      service_name: 'progress-tracking-service'
      image_tag: ${{ github.sha }}
      helm_repo: "https://github.com/AcademiaY4/CogniCare-Manifest.git"
      service_folder: "progress-tracking-service"
    secrets:
      MANIFEST_REPO: AcademiaY4/CogniCare-Manifest
      MANIFEST_BRANCH: master
      PAT_FOR_MANIFEST: ${{ secrets.PAT_FOR_MANIFEST }}
