name: "Reusable: Push Docker"

on:
  workflow_call:
    inputs:
      docker_tag:
        required: true
        type: string
    secrets:
      GCP_CREDS:
        required: true
      GAR_REGION:
        required: true

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: 'Auth to GCP'
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDS }}

      - name: 'Docker Auth To GAR'
        run: gcloud auth configure-docker "${{ secrets.GAR_REGION }}-docker.pkg.dev"

      - name: 'Push Docker Image'
        run: docker push "${{ inputs.docker_tag }}"