name: "Reusable: Push Docker"

on:
  workflow_call:
    inputs:
      docker_tag:
        required: true
        type: string
  
    secrets:
      GCP_CREDS:
        required: true
      PROJECT_ID:
        required: true
      GAR_REGION:
        required: true
      FE_GAR_IMAGE_NAME:
        required: true
      FE_GAR_REPO_NAME:
        required: true

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: 'Auth to GCP'
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDS }}

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2

      - name: 'Docker Auth To GAR'
        run: gcloud auth configure-docker "${{ secrets.GAR_REGION }}-docker.pkg.dev"

      - name: 'Push Docker Image'
        run: docker push "${{ secrets.GAR_REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.FE_GAR_REPO_NAME }}/${{ secrets.FE_GAR_IMAGE_NAME }}:${{ inputs.docker_tag }}"