name: 'Progress Tracking Service CI'

on:
  push:
    branches:
      - master
    paths:
      - 'backend/progress-tracking-service/**'
  pull_request:
    branches:
      - master
    paths:
      - 'backend/progress-tracking-service/**'

env:
  PROJECT_ID: '${{ secrets.PROJECT_ID }}'
  GAR_IMAGE_NAME: '${{ secrets.TPS_GAR_IMAGE_NAME }}'
  GAR_REPO_NAME: '${{ secrets.TPS_GAR_REPO_NAME }}'
  GAR_REGION: '${{ secrets.GAR_REGION }}'

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - name: 'Authenticate to GCP'
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDS }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Docker Auth To GAR'
        run: |
          gcloud auth configure-docker "${{env.GAR_REGION}}-docker.pkg.dev"

      - name: 'Build and Push To GAR'
        run: |-
          DOCKER_TAG="${{ env.GAR_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPO_NAME }}/${{ env.GAR_IMAGE_NAME }}:${{ github.sha }}"
          docker build --tag "${DOCKER_TAG}" ./backend/treatment-planning-service
          docker push "${DOCKER_TAG}"