name: "Reusable: Trivy Scan"

on:
  workflow_call:
    inputs:
      image_ref:
        required: true
        type: string

jobs:
  trivy:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:

      - name: Print image ref for debug 🐞
        run: echo "IMAGE_REF=${{ inputs.image_ref }}"
        
      - name: Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          image-ref: ${{ inputs.image_ref }}
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'HIGH,CRITICAL'
          exit-code: '1'
          ignore-unfixed: true

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'