name: 'Trivy Image Scanning'

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string

permissions:
  security-events: write

jobs:
  trivy_scan:
    runs-on: ubuntu-latest

    steps:
      - name: 'Set up Trivy'
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin v0.57.0

      - name: 'Scan Docker Image with Trivy'
        run: |
          trivy image --format sarif -o trivy-results.sarif "${{ inputs.image }}"

      - name: 'Upload SARIF Report to GitHub'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif
