# .github/workflows/trivy-scan.yaml
name: 'Trivy Security Scan'

on:
  workflow_call:
    inputs:
      image_ref:
        required: true
        type: string

permissions:
  security-events: write # Needed for Trivy action to upload SARIF

jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Code (if needed)'
        uses: actions/checkout@v4
        # Conditionally checkout only if the image context requires it
        # For pre-built images, this step might not be necessary.
        # You might need to adjust the 'if' condition based on your use case.
        if: false # Set to true if Trivy needs to access the codebase

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.18.0 # Use a specific version
        with:
          image-ref: ${{ inputs.image_ref }}
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'HIGH,CRITICAL' # Adjust severity as needed
          exit-code: '1' # Fail the workflow step if vulnerabilities are found
          ignore-unfixed: true # Optional: Ignore unfixed vulnerabilities

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always() # Ensure this runs even if Trivy fails
        with:
          sarif_file: 'trivy-results.sarif'