name: "Reusable: Trivy Scan"

on:
  workflow_call:
    inputs:
      image_ref:
        required: true
        type: string
    
    secrets:
      GCP_CREDS:
        required: true
      PROJECT_ID:
        required: true
      GAR_REGION:
        required: true
      FE_GAR_IMAGE_NAME:
        required: true
      FE_GAR_REPO_NAME:
        required: true

jobs:
  trivy:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:

      - name: Print image ref for debug 🐞
        run: echo "IMAGE_REF=${{ inputs.image_ref }}"

      - name: 'Auth to GCP'
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDS }}

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2

      - name: 'Docker Auth To GAR'
        run: gcloud auth configure-docker "${{ secrets.GAR_REGION }}-docker.pkg.dev"

      - name: Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          image-ref: ${{ secrets.GAR_REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.FE_GAR_REPO_NAME }}/${{ secrets.FE_GAR_IMAGE_NAME }}:${{ inputs.docker_tag }}
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'HIGH,CRITICAL'
          exit-code: '1'
          ignore-unfixed: true

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'