# # .github/workflows/trivy-scan.yaml
# name: 'Trivy Security Scan'

# on:
#   workflow_call:
#     inputs:
#       image_ref:
#         required: true
#         type: string

# permissions:
#   security-events: write # Needed for Trivy action to upload SARIF

# jobs:
#   security_scan:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v4

#       - name: Run Trivy vulnerability scanner
#         uses: aquasecurity/trivy-action
#         with:
#           image-ref: ${{ inputs.image_ref }}
#           format: 'sarif'
#           output: 'trivy-results.sarif'
#           severity: 'HIGH,CRITICAL' # Adjust severity as needed
#           exit-code: '1' # Fail the workflow step if vulnerabilities are found
#           ignore-unfixed: true # Optional: Ignore unfixed vulnerabilities

#       - name: Upload Trivy scan results to GitHub Security tab
#         uses: github/codeql-action/upload-sarif@v3
#         if: always() # Ensure this runs even if Trivy fails
#         with:
#           sarif_file: 'trivy-results.sarif'

name: "Reusable: Trivy Scan"

on:
  workflow_call:
    inputs:
      image_ref:
        required: true
        type: string

jobs:
  trivy:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          image-ref: ${{ inputs.image_ref }}
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'HIGH,CRITICAL'
          exit-code: '1'
          ignore-unfixed: true

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'